services:
  yaushserver:
    image: ${DOCKER_REGISTRY-}yaushserver
    build:
        context: .
        dockerfile: Web/Dockerfile
        args:
            BUILD_CONFIGURATION: Debug
    ports:
        - 8080
        - 8081
    environment:
        ASPNETCORE_ENVIRONMENT: Development
        # ASPNETCORE_URLS: https://*:443;http://*:80
        ASPNETCORE_Kestrel__Certificates__Default__Password: ${KESTREL_CERTIFICATE_PASSWORD}
        ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
        ASPNETCORE_ConnectionStrings__YaushDB: Host=db;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Database=yaush;
    volumes:
        - ~/.aspnet/https:/https:ro
  db:
    image: postgres:17.5-alpine
    volumes:
        - database:/var/lib/postgres/data
    ports: 
        - 5432:5432
    environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 5
      timeout: 10s
  seq:
    image: datalust/seq:latest
    ports:
        - 45341:443
        - 5341:80
    environment:
        ACCEPT_EULA: Y
    volumes:
        - seq_data:/data


volumes:
    database:
    seq_data: